/**
 * @license GPL LICENSE
 * Copyright (c) 2021 Thomas Michael Weissel
 * Leaf module: apps that must not run during an exam (kill + remote-assistant keyword detect).
 * Matching is case-insensitive substring on process name/cmdline,
 * EXCEPT macOS pkill -f which is case-sensitive -> TitleCase duplicates are intentional.
 * Sorted alphabetically (case-insensitive). Never add bare 'vnc' (kills vncproxy-helper).
 */
export const appsToClose = [
    'anydesk',
    'brave',
    'ChatGPT',
    'chatgpt',
    'chrome',
    'chrome-remote-desktop',
    'chromeremotedesktop',
    'chromium',
    'claude',
    'Claude',
    'discord',
    'Discord',
    'dwagent',
    'DWAgent',
    'element-desktop',
    'Element',
    'firefox',
    'Firefox',
    'g2comm',
    'GeoGebra',
    'google-chrome',
    'Google Chrome',
    'gpt4all',
    'Grammarly',
    'librewolf',
    'lmstudio',
    'LM Studio',
    'logmein',
    'LogMeIn',
    'megasync',
    'MEGAsync',
    'Microsoft Edge',
    'Microsoft Teams',
    'ms-teams',
    'ms-teams_modulehost',
    'ms-teamsupdate',
    'msteams',
    'msteams_autostarter',
    'msedge',
    'msedgewebview2',
    'mstsc',
    'NAV',
    'nomachine',
    'NoMachine',
    'NortonSecurity',
    'ollama',
    'Ollama',
    'opera',
    'parallels',
    'Parallels',
    'parsec',
    'Parsec',
    'pcvisit',
    'perplexity',
    'Perplexity',
    'realvnc',
    'RealVNC',
    'remoteutilities',
    'rustdesk',
    'RustDesk',
    'safari',
    'screenconnect',
    'ScreenConnect',
    'signal-desktop',
    'Signal',
    'skype',
    'skypeforlinux',
    'Skype',
    'slack',
    'Slack',
    'splashtop',
    'Splashtop',
    'steam',
    'Steam',
    'steamwebhelper',
    'SteamWebHelper',
    'support 15',
    'syncthing',
    'Teams',
    'teams',
    'teamviewer',
    'TeamViewer',
    'telegram-desktop',
    'Telegram',
    'tigervnc',
    'tor-browser',
    'Tor Browser',
    'viber',
    'Viber',
    'vivaldi',
    'Vivaldi',
    'vncviewer',
    'waterfox',
    'webex',
    'Webex',
    'whatsapp',
    'WhatsApp',
    'windsurf',
    'Windsurf',
    'zoho',
    'Zoho',
    'zoom',
    'zoom.us',
    'Zoom'
];
