
name: Build current Linux Main Branch

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Teacher install dependencies
      working-directory: ./teacher
      run: npm install
    - name: Teacher install build
      working-directory: ./teacher
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: teacher-current-main-linux
        path: |
          ./release/
          !./release/**/linux-unpacked
        retention-days: 1

