name: Build Linux Prelease Artefact

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: BiP-org/next-exam
          ref: main
          token: ${{ secrets.PAT_USER_ADMINISTRATION }}
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Teacher cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./teacher/.npm
            ./teacher/node_modules
          key: ${{ runner.os }}-node-t-${{ hashFiles('./teacher/**/package-lock.json') }}
      - name: Teacher install dependencies
        working-directory: ./teacher
        run: npm install
      - name: Teacher build
        working-directory: ./teacher
        run: npm run build:linux
      - name: Student cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./student/.npm
            ./student/node_modules
          key: ${{ runner.os }}-node-s-${{ hashFiles('./student/**/package-lock.json') }}
      - name: Student install dependencies
        working-directory: ./student
        run: npm install
      - name: Student build
        working-directory: ./student
        run: npm run build:linux


      - name: Upload Student Linux x64 AppImage
        uses: actions/upload-artifact@v4
        with:
          name: next-exam-student-linux-x64-appimage
          path: ./release/**/Next-Exam-Student*x86_64.AppImage
          retention-days: 5

      - name: Upload Teacher Linux x64 AppImage
        uses: actions/upload-artifact@v4
        with:
          name: next-exam-teacher-linux-x64-appimage
          path: ./release/**/Next-Exam-Teacher*x86_64.AppImage
          retention-days: 5
