
name: Build current Main Branch with Node.js CI

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
    - name: Teacher install dependencies
      working-directory: ./teacher
      run: npm install
    - name: Teacher build
      working-directory: ./teacher
      run: npm run build --if-present