name: Final Release Trigger
on: 
  workflow_dispatch:

# opt in to Node 24 runtime for js actions (default from 2026-06-16); pre-validate
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow registriert."